/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TicketsRouteImport } from './routes/tickets'
import { Route as SupportRouteImport } from './routes/support'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as ReportsRouteImport } from './routes/reports'
import { Route as PassengersRouteImport } from './routes/passengers'
import { Route as OffersRouteImport } from './routes/offers'
import { Route as NewBookingRouteImport } from './routes/new-booking'
import { Route as LoginRouteImport } from './routes/login'
import { Route as BookingHistoryRouteImport } from './routes/booking-history'
import { Route as IndexRouteImport } from './routes/index'

const TicketsRoute = TicketsRouteImport.update({
  id: '/tickets',
  path: '/tickets',
  getParentRoute: () => rootRouteImport,
} as any)
const SupportRoute = SupportRouteImport.update({
  id: '/support',
  path: '/support',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const ReportsRoute = ReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => rootRouteImport,
} as any)
const PassengersRoute = PassengersRouteImport.update({
  id: '/passengers',
  path: '/passengers',
  getParentRoute: () => rootRouteImport,
} as any)
const OffersRoute = OffersRouteImport.update({
  id: '/offers',
  path: '/offers',
  getParentRoute: () => rootRouteImport,
} as any)
const NewBookingRoute = NewBookingRouteImport.update({
  id: '/new-booking',
  path: '/new-booking',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const BookingHistoryRoute = BookingHistoryRouteImport.update({
  id: '/booking-history',
  path: '/booking-history',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/booking-history': typeof BookingHistoryRoute
  '/login': typeof LoginRoute
  '/new-booking': typeof NewBookingRoute
  '/offers': typeof OffersRoute
  '/passengers': typeof PassengersRoute
  '/reports': typeof ReportsRoute
  '/settings': typeof SettingsRoute
  '/support': typeof SupportRoute
  '/tickets': typeof TicketsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/booking-history': typeof BookingHistoryRoute
  '/login': typeof LoginRoute
  '/new-booking': typeof NewBookingRoute
  '/offers': typeof OffersRoute
  '/passengers': typeof PassengersRoute
  '/reports': typeof ReportsRoute
  '/settings': typeof SettingsRoute
  '/support': typeof SupportRoute
  '/tickets': typeof TicketsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/booking-history': typeof BookingHistoryRoute
  '/login': typeof LoginRoute
  '/new-booking': typeof NewBookingRoute
  '/offers': typeof OffersRoute
  '/passengers': typeof PassengersRoute
  '/reports': typeof ReportsRoute
  '/settings': typeof SettingsRoute
  '/support': typeof SupportRoute
  '/tickets': typeof TicketsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/booking-history'
    | '/login'
    | '/new-booking'
    | '/offers'
    | '/passengers'
    | '/reports'
    | '/settings'
    | '/support'
    | '/tickets'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/booking-history'
    | '/login'
    | '/new-booking'
    | '/offers'
    | '/passengers'
    | '/reports'
    | '/settings'
    | '/support'
    | '/tickets'
  id:
    | '__root__'
    | '/'
    | '/booking-history'
    | '/login'
    | '/new-booking'
    | '/offers'
    | '/passengers'
    | '/reports'
    | '/settings'
    | '/support'
    | '/tickets'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BookingHistoryRoute: typeof BookingHistoryRoute
  LoginRoute: typeof LoginRoute
  NewBookingRoute: typeof NewBookingRoute
  OffersRoute: typeof OffersRoute
  PassengersRoute: typeof PassengersRoute
  ReportsRoute: typeof ReportsRoute
  SettingsRoute: typeof SettingsRoute
  SupportRoute: typeof SupportRoute
  TicketsRoute: typeof TicketsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/tickets': {
      id: '/tickets'
      path: '/tickets'
      fullPath: '/tickets'
      preLoaderRoute: typeof TicketsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/support': {
      id: '/support'
      path: '/support'
      fullPath: '/support'
      preLoaderRoute: typeof SupportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reports': {
      id: '/reports'
      path: '/reports'
      fullPath: '/reports'
      preLoaderRoute: typeof ReportsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/passengers': {
      id: '/passengers'
      path: '/passengers'
      fullPath: '/passengers'
      preLoaderRoute: typeof PassengersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/offers': {
      id: '/offers'
      path: '/offers'
      fullPath: '/offers'
      preLoaderRoute: typeof OffersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/new-booking': {
      id: '/new-booking'
      path: '/new-booking'
      fullPath: '/new-booking'
      preLoaderRoute: typeof NewBookingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/booking-history': {
      id: '/booking-history'
      path: '/booking-history'
      fullPath: '/booking-history'
      preLoaderRoute: typeof BookingHistoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BookingHistoryRoute: BookingHistoryRoute,
  LoginRoute: LoginRoute,
  NewBookingRoute: NewBookingRoute,
  OffersRoute: OffersRoute,
  PassengersRoute: PassengersRoute,
  ReportsRoute: ReportsRoute,
  SettingsRoute: SettingsRoute,
  SupportRoute: SupportRoute,
  TicketsRoute: TicketsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
